[[Base]]
  Sel = "Layer"
  Desc = "generic params for all layers"
  [Base.Params]
    "Layer.Acts.Clamp.Ge" = "1.5"

[[Base]]
  Sel = ".PFCLayer"
  Desc = "pfc layers: slower trgavgact"
  [Base.Params]
    "Layer.Learn.TrgAvgAct.SynScaleRate" = "0.0002"

[[Base]]
  Sel = ".PTMaintLayer"
  Desc = "time integration params"
  [Base.Params]
    "Layer.Acts.Dend.ModGain" = "1.5"
    "Layer.Inhib.Layer.Gi" = "2.4"
    "Layer.Inhib.Pool.Gi" = "2.4"
    "Layer.Learn.NeuroMod.AChDisInhib" = "0.0"

[[Base]]
  Sel = ".PTPredLayer"
  Desc = ""
  [Base.Params]
    "Layer.CT.DecayTau" = "50"
    "Layer.CT.GeGain" = "0.05"
    "Layer.Inhib.ActAvg.Nominal" = "0.1"
    "Layer.Learn.NeuroMod.AChDisInhib" = "0"

[[Base]]
  Sel = ".CS"
  Desc = "need to adjust Nominal for number of CSs -- now down automatically"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.1"

[[Base]]
  Sel = "#OFCposUS"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Pool.Gi" = "1"

[[Base]]
  Sel = "#OFCposUSPT"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.2"
    "Layer.Inhib.Pool.Gi" = "3.0"

[[Base]]
  Sel = "#OFCposUSPTp"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Pool.Gi" = "1.4"

[[Base]]
  Sel = "#OFCnegUS"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.1"
    "Layer.Inhib.Layer.Gi" = "1.2"

[[Base]]
  Sel = "#OFCnegUSPT"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.2"
    "Layer.Inhib.Pool.Gi" = "3.0"

[[Base]]
  Sel = "#OFCnegUSPTp"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Pool.Gi" = "1.4"

[[Base]]
  Sel = "#OFCposVal"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Pool.Gi" = "1"

[[Base]]
  Sel = ".MatrixLayer"
  Desc = "all mtx"
  [Base.Params]
    "Layer.Acts.Dend.ModGain" = "1"
    "Layer.Inhib.Layer.On" = "false"
    "Layer.Inhib.Pool.FB" = "1"
    "Layer.Inhib.Pool.Gi" = "0.3"

[[Base]]
  Sel = "#BLAPosAcqD1"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "2.4"
    "Layer.Inhib.Pool.Gi" = "1"

[[Base]]
  Sel = "#BLANegAcqD2"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "1.2"

[[Base]]
  Sel = ".VSPatchLayer"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Pool.FB" = "0"
    "Layer.Inhib.Pool.Gi" = "0.5"
    "Layer.Learn.NeuroMod.DipGain" = "1"
    "Layer.Learn.RLRate.SigmoidMin" = "0.01"
    "Layer.Learn.TrgAvgAct.GiBaseInit" = "0.5"
    "Layer.VSPatch.Gain" = "3"
    "Layer.VSPatch.ThrInit" = "0.15"
    "Layer.VSPatch.ThrLRate" = "0.001"
    "Layer.VSPatch.ThrNonRew" = "10"

[[Base]]
  Sel = ".LDTLayer"
  Desc = ""
  [Base.Params]
    "Layer.LDT.MaintInhib" = "2.0"

[[Base]]
  Sel = "#SC"
  Desc = ""
  [Base.Params]
    "Layer.Acts.KNa.Slow.Max" = "0.05"

[[Base]]
  Sel = ".PFCPrjn"
  Desc = "pfc prjn params -- more robust to long-term training"
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.01"
    "Prjn.Learn.Trace.SubMean" = "1"

[[Base]]
  Sel = ".PTtoPred"
  Desc = "stronger drive on pt pred"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "6"

[[Base]]
  Sel = "#BLAPosAcqD1ToOFCposUS"
  Desc = "stronger"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1.5"

[[Base]]
  Sel = "#OFCposUSToOFCposVal"
  Desc = "stronger"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "3"

[[Base]]
  Sel = "#ACCnegValToACCutil"
  Desc = "stronger"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "3"

[[Base]]
  Sel = "#OFCposValToACCutil"
  Desc = "not good to make this stronger"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1"

[[Base]]
  Sel = ".PTSelfMaint"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.0001"
    "Prjn.PrjnScale.Abs" = "4"

[[Base]]
  Sel = ".ToPTp"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "4"

[[Base]]
  Sel = ".BLAFromNovel"
  Desc = "must be strong enough to compete with CS at start -- now done automatically"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "3"

[[Base]]
  Sel = ".MatrixPrjn"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.Trace.LearnThr" = "0.0"
    "Prjn.Matrix.NoGateLRate" = "1"

[[Base]]
  Sel = ".ToSC"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "2"

[[Base]]
  Sel = ".DrivesToMtx"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1"

[[Base]]
  Sel = ".BLAExtPrjn"
  Desc = "ext learns relatively fast"
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.005"

[[Base]]
  Sel = ".BLAAcqToGo"
  Desc = "must dominate"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "2"
    "Prjn.PrjnScale.Rel" = "1"

[[Base]]
  Sel = ".BLAExtToAcq"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "0.5"

[[Base]]
  Sel = ".PFCToVSMtx"
  Desc = "contextual, should be weaker"
  [Base.Params]
    "Prjn.PrjnScale.Rel" = "0.1"

[[Base]]
  Sel = ".VSPatchPrjn"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.05"
    "Prjn.PrjnScale.Abs" = "2"

[[Base]]
  Sel = "#CSToBLAPosAcqD1"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.1"

[[Base]]
  Sel = ".SuperToThal"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "4"

[[Base]]
  Sel = ".SuperToPT"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "0.5"

[[Base]]
  Sel = "#ACCnegValToACCnegValMD"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "3"

[[Base]]
  Sel = ".GPiToBGThal"
  Desc = "inhibition from GPi to MD"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "5"

[[Base]]
  Sel = "#UrgencyToVsMtxGo"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "4"
