GUI = false
Debug = false

[Env]
  RunName = "PosAcq_A100"
  SetNBlocks = true
  NBlocks = 50

[Params]
  Sheet = ""
  Tag = ""
  Note = ""
  File = ""
  SaveAll = false
  Good = true
  [Params.PVLV]
    "Urgency.U50" = 10

[Run]
  GPU = false
  NThreads = 2
  Run = 0
  NRuns = 1

[Log]
  AggStats = ["DA", "VSPatch"]
  SaveWts = false
  Block = true
  Cond = true
  Trial = false
  NetData = false
