[[Base]]
  Sel = ".InputLayer"
  Desc = ""
  [Base.Params]
    "Layer.Acts.Decay.Act" = "1.0"
    "Layer.Acts.Decay.Glong" = "1.0"

[[Base]]
  Sel = "#CS"
  Desc = "expect act"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.05"

[[Base]]
  Sel = "#ContextIn"
  Desc = "expect act"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.025"

[[Base]]
  Sel = ".VSPatchLayer"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "0.5"
    "Layer.Inhib.Pool.Gi" = "0.5"
    "Layer.Learn.NeuroMod.AChLRateMod" = "0"
    "Layer.Learn.NeuroMod.DipGain" = "1"
    "Layer.Learn.RLRate.SigmoidMin" = "0.05"
    "Layer.Learn.TrgAvgAct.GiBaseInit" = "0"

[[Base]]
  Sel = ".VTALayer"
  Desc = ""
  [Base.Params]
    "Layer.VTA.AChThr" = "0.5"
    "Layer.VTA.CeMGain" = "0.75"
    "Layer.VTA.LHbGain" = "1.25"

[[Base]]
  Sel = ".MatrixLayer"
  Desc = "all mtx"
  [Base.Params]
    "Layer.Acts.Kir.Gbar" = "2"
    "Layer.Learn.RLRate.Diff" = "false"
    "Layer.Learn.RLRate.On" = "true"

[[Base]]
  Sel = "#BLAPosExtD2"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "1.8"
    "Layer.Inhib.Pool.Gi" = "1.0"

[[Base]]
  Sel = ".PTMaintLayer"
  Desc = "time integration params"
  [Base.Params]
    "Layer.Acts.Dend.ModGain" = "1.5"
    "Layer.Inhib.Layer.Gi" = "3.0"
    "Layer.Inhib.Pool.Gi" = "3.6"

[[Base]]
  Sel = ".PTSelfMaint"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "4.0"

[[Base]]
  Sel = "#OFCposUSPTToOFCposUSPT"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "5"

[[Base]]
  Sel = ".PTPredLayer"
  Desc = ""
  [Base.Params]
    "Layer.CT.GeGain" = "0.05"

[[Base]]
  Sel = ".LDTLayer"
  Desc = ""
  [Base.Params]
    "Layer.LDT.MaintInhib" = "0.8"

[[Base]]
  Sel = "#OFCposUSPTp"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Pool.Gi" = "1.0"

[[Base]]
  Sel = "#OFCposUSPT"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Pool.Gi" = "3.6"

[[Base]]
  Sel = "#SC"
  Desc = ""
  [Base.Params]
    "Layer.Acts.KNa.Slow.Max" = "0.5"

[[Base]]
  Sel = "#ContextInToBLAPosExtD2"
  Desc = "specific to this project"
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.1"
    "Prjn.PrjnScale.Abs" = "4"

[[Base]]
  Sel = ".VSMatrixPrjn"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.Trace.LearnThr" = "0.1"

[[Base]]
  Sel = ".SuperToThal"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "4.0"

[[Base]]
  Sel = ".BLAExtPrjn"
  Desc = ""
  [Base.Params]
    "Prjn.BLA.NegDeltaLRate" = "1"
    "Prjn.Learn.LRate.Base" = "0.005"

[[Base]]
  Sel = ".BLAExtToAcq"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1"

[[Base]]
  Sel = ".GPiToBGThal"
  Desc = "inhibition from GPi to MD"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "3"

[[Base]]
  Sel = ".PTpToBLAExt"
  Desc = "modulatory, drives extinction learning based on maintained goal rep"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "0.5"

[[Base]]
  Sel = "#BLAPosAcqD1ToOFCposUS"
  Desc = "strong, high variance"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "2"

[[Base]]
  Sel = ".BLAAcqToGo"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "4"

[[Base]]
  Sel = ".BLAExtToAcq"
  Desc = "fixed inhibitory"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1.0"

[[Base]]
  Sel = ".VSPatchPrjn"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.05"
    "Prjn.Learn.Trace.LearnThr" = "0"
    "Prjn.PrjnScale.Abs" = "3"

[[Base]]
  Sel = ".ToPTp"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "2"
