[[Base]]
  Sel = "Layer"
  Desc = "clamp gain makes big diff on overall excitation, gating propensity"
  [Base.Params]
    "Layer.Acts.Clamp.Ge" = "1.0"

[[Base]]
  Sel = ".VBG"
  Desc = "all ModACh"
  [Base.Params]
    "Layer.Acts.Dend.ModACh" = "true"

[[Base]]
  Sel = ".MatrixLayer"
  Desc = "all mtx"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.25"
    "Layer.Inhib.Pool.On" = "false"
    "Layer.Learn.RLRate.Diff" = "false"
    "Layer.Learn.RLRate.On" = "true"
    "Layer.Learn.TrgAvgAct.On" = "true"
    "Layer.Matrix.IsVS" = "true"

[[Base]]
  Sel = ".PTMaintLayer"
  Desc = "time integration params"
  [Base.Params]
    "Layer.Acts.Dend.ModACh" = "true"
    "Layer.Acts.Dend.ModGain" = "1.5"
    "Layer.Acts.Kir.Gbar" = "0"
    "Layer.Inhib.Layer.Gi" = "3.2"

[[Base]]
  Sel = ".VSMatrixPrjn"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.01"
    "Prjn.Learn.Trace.LearnThr" = "0.1"
    "Prjn.Matrix.VSRewLearn" = "false"
    "Prjn.SWts.Adapt.On" = "false"
  [Base.Hypers]
    [Base.Hypers."Prjn.Learn.LRate.Base"]
      Tweak = "-"
    [Base.Hypers."Prjn.Learn.Trace.LearnThr"]
      Tweak = "-"

[[Base]]
  Sel = "#UrgencyToVMtxGo"
  Desc = "strong urgency factor"
  [Base.Params]
    "Prjn.Learn.Learn" = "false"
    "Prjn.PrjnScale.Abs" = "0"
    "Prjn.PrjnScale.Rel" = "0.1"

[[Base]]
  Sel = ".SuperToPT"
  Desc = "one-to-one from super"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "0.5"

[[Base]]
  Sel = ".PTSelfMaint"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "4"

[[Base]]
  Sel = ".SuperToThal"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "3.0"

[[Base]]
  Sel = ".ACCToVMtx"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1.5"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = "#VMtxNoToVMtxGo"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.Learn" = "false"
    "Prjn.PrjnScale.Abs" = "1"
    "Prjn.PrjnScale.Rel" = "0.05"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Rel"]
      Tweak = "log"
