# agent must choose between various CSs that satisfy the same drive but are at different distances.

# TODO: is distance a function of the arm or the CS or both?

NArms = 8
NDrives = 4
NCSs = 8
ArmLengths.Min = 4
ArmLengths.Max = 8
GroupMinMax = true

