[[Base]]
  Sel = "Layer"
  Desc = "clamp gain makes big diff on overall excitation, gating propensity"
  [Base.Params]
    "Layer.Acts.Clamp.Ge" = "1.0"
    "Layer.Acts.Noise.Ge" = "0.0001"
    "Layer.Acts.Noise.Gi" = "0.0001"
    "Layer.Acts.Noise.On" = "true"
  [Base.Hypers]
    [Base.Hypers."Layer.Acts.Noise.Ge"]
      Tweak = "-"

[[Base]]
  Sel = ".MatrixLayer"
  Desc = "all mtx"
  [Base.Params]
    "Layer.Inhib.Pool.Gi" = "0.5"
    "Layer.Learn.NeuroMod.BurstGain" = "0.1"
  [Base.Hypers]
    [Base.Hypers."Layer.Acts.Kir.Gbar"]
      Tweak = "-"
    [Base.Hypers."Layer.Inhib.Pool.Gi"]
      Tweak = "-"
    [Base.Hypers."Layer.Learn.NeuroMod.BurstGain"]
      Tweak = "-"

[[Base]]
  Sel = ".DSTNLayer"
  Desc = "all STN"
  [Base.Params]
    "Layer.Acts.Init.GeBase" = "0.1"
    "Layer.Acts.Kir.Gbar" = "10"
    "Layer.Acts.SKCa.Gbar" = "2"
    "Layer.Inhib.Layer.Gi" = "0.5"
    "Layer.Inhib.Layer.On" = "true"
    "Layer.Learn.NeuroMod.AChDisInhib" = "0"
  [Base.Hypers]
    [Base.Hypers."Layer.Acts.Init.GeBase"]
      Tweak = "-"
    [Base.Hypers."Layer.Acts.Kir.Gbar"]
      Tweak = "-"
    [Base.Hypers."Layer.Acts.SKCa.Gbar"]
      Tweak = "-"

[[Base]]
  Sel = "#M1VM"
  Desc = "all mtx"
  [Base.Params]
    "Layer.Learn.NeuroMod.AChDisInhib" = "0"

[[Base]]
  Sel = ".PTMaintLayer"
  Desc = "time integration params"
  [Base.Params]
    "Layer.Acts.Dend.ModGain" = "1.0"
    "Layer.Acts.Kir.Gbar" = "0"
    "Layer.Acts.MaintNMDA.Gbar" = "0.007"
    "Layer.Inhib.Layer.Gi" = "2.2"

[[Base]]
  Sel = "#MotorBS"
  Desc = ""
  [Base.Params]
    "Layer.Acts.Clamp.Ge" = "2"
    "Layer.Inhib.Layer.Gi" = "0.2"
    "Layer.Inhib.Layer.On" = "true"
    "Layer.Inhib.Pool.On" = "false"
  [Base.Hypers]
    [Base.Hypers."Layer.Acts.Clamp.Ge"]
      Tweak = "-"

[[Base]]
  Sel = "#DGPeAk"
  Desc = "arkypallidal"
  [Base.Params]
    "Layer.Acts.Init.GeBase" = "0.2"
    "Layer.Acts.Init.GeVar" = "0.1"
  [Base.Hypers]
    [Base.Hypers."Layer.Acts.Init.GeBase"]
      Tweak = "-"
    [Base.Hypers."Layer.Acts.Init.GeVar"]
      Tweak = "-"

[[Base]]
  Sel = ".DSMatrixPrjn"
  Desc = ""
  [Base.Params]
    "Prjn.Learn.LRate.Base" = "0.005"
    "Prjn.Learn.Trace.LearnThr" = "0.1"
    "Prjn.Matrix.BasePF" = "0.005"
    "Prjn.Matrix.Credit" = "0.6"
    "Prjn.Matrix.Delta" = "1"
    "Prjn.PrjnScale.Abs" = "1.8"
  [Base.Hypers]
    [Base.Hypers."Prjn.Learn.LRate.Base"]
      Tweak = "-"
    [Base.Hypers."Prjn.Matrix.BasePF"]
      Tweak = "-"
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = ".SuperToPT"
  Desc = "one-to-one from super"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "0.5"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = ".PTSelfMaint"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = ".SuperToThal"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "3.0"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = ".ToM1"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1.5"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = "#StateToM1"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = "#DGPiToPF"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "0.4"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = "#MotorBSToPF"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = "#DGPiToM1VM"
  Desc = "final inhibition"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "2"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = "#DGPiToMotorBS"
  Desc = "final inhibition"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "3"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = ".M1ToMotorBS"
  Desc = ""
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "2"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = "#M1PTToMotorBS"
  Desc = "PT to motor is strong, key"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "2"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = "#M1ToMotorBS"
  Desc = "weaker; note: this is a proxy for cerebellum etc inputs"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "1.5"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[Base]]
  Sel = "#DGPeAkToDMtxNo"
  Desc = "go disinhibition"
  [Base.Params]
    "Prjn.PrjnScale.Abs" = "6"
  [Base.Hypers]
    [Base.Hypers."Prjn.PrjnScale.Abs"]
      Tweak = "-"

[[NoiseOff]]
  Sel = "Layer"
  Desc = "turn off noise"
  [NoiseOff.Params]
    "Layer.Acts.Noise.On" = "false"
