Includes = []
GUI = false
Debug = false
OpenWts = ''

[Env]
  Config = ''
  NDrives = 4
  PctCortexStEpc = 10
  PctCortexNEpc = 1
  PctCortex = 0.0
  SameSeed = false

[Params]
  Sheet = ''
  Tag = ''
  Note = ''
  File = ''
  SaveAll = false
  Good = true

[Run]
  GPU = true
  NData = 16
  NThreads = 0
  Run = 0
  NRuns = 5
  NEpochs = 100
  NTrials = 128
  NCycles = 300
  PCAInterval = 10

[Log]
  AggStats = [
    'Rew_R',
    'DA_R',
    'RewPred_R',
    'VtaDA',
    'PVposEst',
    'PVnegEst',
    'PVposVar',
    'PVnegVar'
  ]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  NetData = false
  Testing = false
