# Each CS is assigned to 2 locations.
# At one location, it has P(reward) = 1, at the other P(reward) = 0.5.

NArms = 4
NDrives = 4
NCSs = 8
NUSs = 8

[[USs]]
	Prob = 1.0

[[USs]]
	Prob = 1.0

[[USs]]
	Prob = 1.0

[[USs]]
	Prob = 1.0

[[USs]]
	Prob = 0.5

[[USs]]
	Prob = 0.5

[[USs]]
	Prob = 0.5

[[USs]]
	Prob = 0.5
