ID = 'com.emer.axon.v2'
Name = 'axon'
Type = 'Library'
Version = 'v2.0.0-dev0.0.5'

[Generate]
  [Generate.Enumgen]
    AcceptLower = true
    LineComment = true

  [Generate.Gtigen]
    AddTypes = true

[Release]
  Package = 'axon'
  VersionFile = 'axon/version.go'

[Web]
  LoadingLabel = ''
  RandomVersion = false
