---
name: Build

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - 'master'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Mount bazel action cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Mount bazel repo cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel-repo"
          key: bazel-repo
      - name: bazel test //...
        env:
          # Bazelisk will download bazel to here, ensure it is under .cache dir.
          XDG_CACHE_HOME: /home/runner/.cache/bazel-repo
        run: bazel --bazelrc=.github/workflows/workflows.bazelrc test //...
